import { AppHeader } from "@/components/AppHeader";
import { getSession } from "@/lib/auth";
import { db } from "@/lib/db";
import Link from "next/link";
import { redirect } from "next/navigation";
import { MitigationCard } from "@/components/MitigationCard";

export default async function MitigationPlansPage() {
  const session = await getSession();

  if (!session?.companyId) {
    redirect("/sign-in");
  }

  // Fetch Risk Cases and their associated scenarios
  const riskCases = await db.riskCase.findMany({
    where: { companyId: session.companyId },
    include: {
      scenarios: true,
      mitigationPlans: true,
    },
    orderBy: { createdAt: "desc" },
  });

  const activeCases = riskCases.filter((rc) => rc.scenarios.length > 0);

  return (
    <div className="stack" style={{ gap: "2rem", maxWidth: "1200px" }}>
      <AppHeader
        title="Mitigation Plans"
        subtitle="Review, simulate, and approve autonomous actions generated by the Reasoning Agent."
      />

      {activeCases.length === 0 ? (
        <section className="card stack" style={{ padding: "3rem 2rem", textAlign: "center", alignItems: "center" }}>
          <div style={{ width: "64px", height: "64px", borderRadius: "50%", backgroundColor: "var(--surface-soft)", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: "1rem" }}>
            <span style={{ fontSize: "1.5rem" }}>🛡️</span>
          </div>
          <h3>No Active Mitigations Pending</h3>
          <p className="muted" style={{ maxWidth: "500px", lineHeight: 1.5, marginTop: "0.5rem" }}>
            When the Risk Agent detects a critical disruption in the Event Fusion Log, it will synthesize a multi-variable tradeoff simulation here for your approval.
          </p>

          <Link href="/dashboard/triggered-risk" className="btn primary" style={{ marginTop: "2rem" }}>
            View Event Fusion Log
          </Link>
        </section>
      ) : (
        <div className="stack" style={{ gap: "2rem" }}>
          {activeCases.map((rc) => (
            <MitigationCard key={rc.id} riskCase={rc} />
          ))}
        </div>
      )}
    </div>
  );
}
